import '../core/models/spot.dart';
import '../core/models/spot_category.dart';

class SeedData {
  static List<Spot> getPhiladelphiaSpots() {
    return [
      // University of Pennsylvania Area (Higher Concentration)
      Spot(
        id: 'seed_1',
        title: 'Penn Park Schuylkill Overlook',
        description: 'The elevated northeast corner of Penn Park offers stunning views of the Schuylkill River and downtown skyline, especially beautiful during sunset.',
        latitude: 39.9486,
        longitude: -75.1903,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 12, 15, 16, 30),
        tags: ['river', 'skyline', 'sunset', 'university'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),
      Spot(
        id: 'seed_2',
        title: 'Locust Walk Button Tradition Spot',
        description: 'The exact spot on Locust Walk where the famous Penn tradition of rubbing the button on the Ben Franklin statue brings good luck.',
        latitude: 39.9522,
        longitude: -75.1932,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 12, 10, 14, 15),
        tags: ['tradition', 'ben-franklin', 'statue', 'luck'],
        viewCount: 289,
        bookmarkCount: 52,
        visitCount: 134,
      ),
      Spot(
        id: 'seed_3',
        title: 'College Green Secret Garden',
        description: 'A hidden garden space behind College Hall accessible through a narrow pathway, featuring original 1870s landscaping.',
        latitude: 39.9530,
        longitude: -75.1925,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 12, 5, 11, 20),
        tags: ['hidden', 'garden', 'college-hall', '1870s'],
        viewCount: 167,
        bookmarkCount: 31,
        visitCount: 78,
      ),
      Spot(
        id: 'seed_4',
        title: 'Penn Museum Rooftop Terrace',
        description: 'The rarely-visited rooftop terrace of the Penn Museum offers panoramic views and occasional public access during special events.',
        latitude: 39.9499,
        longitude: -75.1906,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1507041957456-9c397ce39c97?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 11, 28, 15, 45),
        tags: ['museum', 'rooftop', 'terrace', 'special-events'],
        viewCount: 203,
        bookmarkCount: 39,
        visitCount: 95,
      ),
      Spot(
        id: 'seed_5',
        title: 'Fisher Fine Arts Library Furness Reading Room',
        description: 'The stunning Gothic Revival reading room designed by Frank Furness, considered one of the most beautiful study spaces in America.',
        latitude: 39.9525,
        longitude: -75.1928,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 11, 22, 9, 30),
        tags: ['library', 'gothic', 'furness', 'reading-room'],
        viewCount: 234,
        bookmarkCount: 47,
        visitCount: 112,
      ),
      Spot(
        id: 'seed_6',
        title: 'Houston Hall Basement Pub',
        description: 'America\'s first student union building houses a historic basement pub where generations of Penn students have gathered.',
        latitude: 39.9517,
        longitude: -75.1934,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 11, 18, 18, 20),
        tags: ['houston-hall', 'first-union', 'basement', 'historic'],
        viewCount: 189,
        bookmarkCount: 36,
        visitCount: 87,
      ),

      // Drexel University Area (Higher Concentration)
      Spot(
        id: 'seed_7',
        title: 'Drexel Park Hidden Amphitheater',
        description: 'A natural amphitheater formed by landscaped hills in Drexel Park, used for outdoor classes and student performances.',
        latitude: 39.9566,
        longitude: -75.1899,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1541919329513-35f7af297129?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 11, 12, 13, 15),
        tags: ['amphitheater', 'park', 'performances', 'classes'],
        viewCount: 156,
        bookmarkCount: 29,
        visitCount: 72,
      ),
      Spot(
        id: 'seed_8',
        title: 'Main Building Clock Tower View',
        description: 'The view from the base of Drexel\'s iconic Main Building clock tower, a perfect spot for architectural photography.',
        latitude: 39.9574,
        longitude: -75.1895,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 11, 8, 16, 40),
        tags: ['clock-tower', 'main-building', 'architecture', 'photography'],
        viewCount: 178,
        bookmarkCount: 34,
        visitCount: 83,
      ),
      Spot(
        id: 'seed_9',
        title: 'Papadakis Integrated Sciences Building Green Roof',
        description: 'The accessible green roof featuring sustainable plantings and city views, demonstrating Drexel\'s environmental commitment.',
        latitude: 39.9559,
        longitude: -75.1889,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 11, 3, 12, 25),
        tags: ['green-roof', 'sustainable', 'environmental', 'sciences'],
        viewCount: 134,
        bookmarkCount: 25,
        visitCount: 61,
      ),
      Spot(
        id: 'seed_10',
        title: 'Drexel Recreation Center Rock Wall',
        description: 'The impressive indoor climbing wall that extends three stories, popular with students and open to the community.',
        latitude: 39.9551,
        longitude: -75.1883,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 10, 28, 14, 50),
        tags: ['climbing', 'recreation', 'three-stories', 'community'],
        viewCount: 212,
        bookmarkCount: 41,
        visitCount: 98,
      ),

      // Temple University Area (Higher Concentration)
      Spot(
        id: 'seed_11',
        title: 'Temple Founder\'s Garden Bell Tower',
        description: 'The historic bell tower in Founder\'s Garden, where the original Temple University bell still rings for special occasions.',
        latitude: 39.9819,
        longitude: -75.1478,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 10, 22, 10, 30),
        tags: ['bell-tower', 'founders-garden', 'historic', 'special-occasions'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 89,
      ),
      Spot(
        id: 'seed_12',
        title: 'Liacouras Walk Cherry Trees',
        description: 'The beautiful cherry tree grove along Liacouras Walk that creates a stunning pink canopy each spring.',
        latitude: 39.9797,
        longitude: -75.1522,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 10, 18, 8, 15),
        tags: ['cherry-trees', 'spring', 'pink-canopy', 'liacouras'],
        viewCount: 245,
        bookmarkCount: 48,
        visitCount: 115,
      ),
      Spot(
        id: 'seed_13',
        title: 'Temple Performing Arts Center Roof Garden',
        description: 'A hidden rooftop garden above the performing arts center with views of North Philadelphia and Center City.',
        latitude: 39.9808,
        longitude: -75.1489,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 10, 12, 17, 20),
        tags: ['rooftop-garden', 'performing-arts', 'north-philly', 'center-city'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 76,
      ),
      Spot(
        id: 'seed_14',
        title: 'Conwell Hall Historic Steps',
        description: 'The grand limestone steps of Temple\'s oldest building, where Russell Conwell first taught and founded the university.',
        latitude: 39.9814,
        longitude: -75.1467,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 10, 8, 11, 45),
        tags: ['conwell-hall', 'limestone', 'oldest-building', 'russell-conwell'],
        viewCount: 198,
        bookmarkCount: 39,
        visitCount: 93,
      ),

      // Saint Joseph\'s University Area (Higher Concentration)
      Spot(
        id: 'seed_15',
        title: 'Saint Joseph\'s Hawk Hill Observatory',
        description: 'The astronomy observatory on Hawk Hill offers public viewing nights and panoramic views of the Main Line.',
        latitude: 40.0381,
        longitude: -75.2392,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1507041957456-9c397ce39c97?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 10, 3, 19, 30),
        tags: ['observatory', 'astronomy', 'hawk-hill', 'main-line'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 72,
      ),
      Spot(
        id: 'seed_16',
        title: 'Barbelin Hall Chapel',
        description: 'The stunning neo-Gothic chapel inside Barbelin Hall featuring beautiful stained glass windows and peaceful acoustics.',
        latitude: 40.0375,
        longitude: -75.2386,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1520637836862-4d197d17c50a?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 9, 28, 14, 20),
        tags: ['chapel', 'neo-gothic', 'stained-glass', 'acoustics'],
        viewCount: 123,
        bookmarkCount: 24,
        visitCount: 58,
      ),
      Spot(
        id: 'seed_17',
        title: 'Maguire Campus Labyrinth',
        description: 'A contemplative stone labyrinth hidden behind the campus center, used for meditation and reflection.',
        latitude: 40.0372,
        longitude: -75.2395,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 9, 22, 16, 10),
        tags: ['labyrinth', 'stone', 'meditation', 'contemplative'],
        viewCount: 189,
        bookmarkCount: 36,
        visitCount: 87,
      ),

      // Jefferson University Area (Higher Concentration)
      Spot(
        id: 'seed_18',
        title: 'Jefferson Alumni Hall Courtyard',
        description: 'The peaceful internal courtyard of Alumni Hall featuring a fountain and seating areas popular with medical students.',
        latitude: 39.9489,
        longitude: -75.1567,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1541919329513-35f7af297129?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 9, 18, 12, 35),
        tags: ['alumni-hall', 'courtyard', 'fountain', 'medical-students'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),
      Spot(
        id: 'seed_19',
        title: 'Jefferson Hospital Historic Amphitheater',
        description: 'The original 1877 surgical amphitheater where Thomas Eakins painted "The Gross Clinic," still used for lectures.',
        latitude: 39.9478,
        longitude: -75.1572,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 9, 12, 15, 50),
        tags: ['amphitheater', '1877', 'thomas-eakins', 'gross-clinic'],
        viewCount: 267,
        bookmarkCount: 51,
        visitCount: 124,
      ),
      Spot(
        id: 'seed_20',
        title: 'Scott Memorial Library Reading Garden',
        description: 'An outdoor reading garden with tables and Wi-Fi, surrounded by medicinal plants used in pharmaceutical education.',
        latitude: 39.9495,
        longitude: -75.1589,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 9, 8, 10, 15),
        tags: ['reading-garden', 'medicinal-plants', 'pharmaceutical', 'wifi'],
        viewCount: 178,
        bookmarkCount: 34,
        visitCount: 82,
      ),

      // Media, PA Area
      Spot(
        id: 'seed_21',
        title: 'Ridley Creek State Park Sycamore Mills Ruins',
        description: 'The stone ruins of the 18th-century Sycamore Mills along Ridley Creek, accessible by a short woodland trail.',
        latitude: 39.8947,
        longitude: -75.4231,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1520637836862-4d197d17c50a?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 9, 3, 14, 25),
        tags: ['mills', 'ruins', '18th-century', 'woodland-trail'],
        viewCount: 201,
        bookmarkCount: 40,
        visitCount: 94,
      ),
      Spot(
        id: 'seed_22',
        title: 'Media Borough Orange Street Bridge',
        description: 'The historic stone arch bridge over Ridley Creek in downtown Media, perfect for photography and creek viewing.',
        latitude: 39.9178,
        longitude: -75.3875,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1507041957456-9c397ce39c97?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 8, 28, 16, 40),
        tags: ['stone-bridge', 'orange-street', 'ridley-creek', 'photography'],
        viewCount: 134,
        bookmarkCount: 26,
        visitCount: 62,
      ),
      Spot(
        id: 'seed_23',
        title: 'Granite Run Mall Overlook Trail',
        description: 'A hiking trail behind the mall leading to an overlook with views across Delaware County toward Philadelphia.',
        latitude: 39.9089,
        longitude: -75.3789,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 8, 22, 11, 15),
        tags: ['hiking-trail', 'overlook', 'delaware-county', 'philadelphia'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),
      Spot(
        id: 'seed_24',
        title: 'Media Theater Historic Courtyard',
        description: 'The charming brick courtyard behind the historic Media Theater, featuring vintage architecture and occasional outdoor events.',
        latitude: 39.9167,
        longitude: -75.3883,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 8, 18, 18, 30),
        tags: ['theater', 'courtyard', 'vintage', 'outdoor-events'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),
      Spot(
        id: 'seed_25',
        title: 'Crum Creek Trail Tyler Arboretum Connection',
        description: 'The trail junction where Crum Creek Trail connects to Tyler Arboretum, featuring a beautiful wooden footbridge.',
        latitude: 39.9234,
        longitude: -75.3967,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 8, 12, 9, 45),
        tags: ['trail-junction', 'tyler-arboretum', 'footbridge', 'wooden'],
        viewCount: 156,
        bookmarkCount: 30,
        visitCount: 73,
      ),

      // Center City Philadelphia
      Spot(
        id: 'seed_26',
        title: 'City Hall Courtyard Secret Garden',
        description: 'The hidden interior courtyard of City Hall with beautiful landscaping and the only quiet spot in the building.',
        latitude: 39.9526,
        longitude: -75.1652,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 8, 8, 13, 20),
        tags: ['city-hall', 'interior-courtyard', 'landscaping', 'quiet'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
      Spot(
        id: 'seed_27',
        title: 'Love Park Underground Concourse',
        description: 'The underground pedestrian concourse beneath Love Park connecting to the subway, featuring rotating art installations.',
        latitude: 39.9543,
        longitude: -75.1657,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 8, 3, 15, 10),
        tags: ['underground', 'concourse', 'subway', 'art-installations'],
        viewCount: 198,
        bookmarkCount: 38,
        visitCount: 92,
      ),
      Spot(
        id: 'seed_28',
        title: 'Reading Terminal Market Clock Tower',
        description: 'The historic clock tower above Reading Terminal Market, visible from the mezzanine level with beautiful architectural details.',
        latitude: 39.9535,
        longitude: -75.1581,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 7, 28, 12, 30),
        tags: ['clock-tower', 'reading-terminal', 'mezzanine', 'architectural'],
        viewCount: 167,
        bookmarkCount: 33,
        visitCount: 78,
      ),
      Spot(
        id: 'seed_29',
        title: 'Rittenhouse Square Fountain Lion Statues',
        description: 'The four bronze lion statues surrounding the central fountain, each with unique expressions and weathering patterns.',
        latitude: 39.9496,
        longitude: -75.1719,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1541919329513-35f7af297129?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 7, 22, 16, 45),
        tags: ['lion-statues', 'bronze', 'fountain', 'unique-expressions'],
        viewCount: 289,
        bookmarkCount: 56,
        visitCount: 134,
      ),
      Spot(
        id: 'seed_30',
        title: 'Washington Square Park Eternal Flame',
        description: 'The eternal flame memorial to unknown Revolutionary War soldiers, surrounded by original cobblestones from the 1700s.',
        latitude: 39.9478,
        longitude: -75.1525,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 7, 18, 14, 20),
        tags: ['eternal-flame', 'revolutionary-war', 'cobblestones', '1700s'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),

      // Old City Philadelphia
      Spot(
        id: 'seed_31',
        title: 'Elfreth\'s Alley Hidden Garden',
        description: 'A tiny colonial garden behind house #124, maintained as it would have appeared in the 18th century with period plants.',
        latitude: 39.9522,
        longitude: -75.1428,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 7, 12, 10, 15),
        tags: ['colonial-garden', 'house-124', '18th-century', 'period-plants'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),
      Spot(
        id: 'seed_32',
        title: 'Christ Church Burial Ground Ben Franklin Grave',
        description: 'Benjamin Franklin\'s grave where visitors throw pennies for luck, creating a unique tradition and photo opportunity.',
        latitude: 39.9511,
        longitude: -75.1456,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1520637836862-4d197d17c50a?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 7, 8, 11, 40),
        tags: ['ben-franklin', 'grave', 'pennies', 'tradition'],
        viewCount: 312,
        bookmarkCount: 61,
        visitCount: 145,
      ),
      Spot(
        id: 'seed_33',
        title: 'Betsy Ross House Courtyard Well',
        description: 'The original colonial well in the courtyard behind the Betsy Ross House, still functioning after 250 years.',
        latitude: 39.9522,
        longitude: -75.1444,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 7, 3, 13, 25),
        tags: ['betsy-ross', 'colonial-well', 'courtyard', '250-years'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),
      Spot(
        id: 'seed_34',
        title: 'Franklin Court Ghost Structure',
        description: 'The steel frame outline of Benjamin Franklin\'s original house, creating a haunting archaeological art installation.',
        latitude: 39.9506,
        longitude: -75.1467,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 6, 28, 15, 50),
        tags: ['ghost-structure', 'steel-frame', 'archaeological', 'art-installation'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),

      // Northern Liberties
      Spot(
        id: 'seed_35',
        title: 'Liberty Lands Park Labyrinth',
        description: 'A community-built stone labyrinth in the heart of the park, surrounded by native wildflower gardens.',
        latitude: 39.9659,
        longitude: -75.1379,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 6, 22, 9, 30),
        tags: ['labyrinth', 'community-built', 'wildflower', 'native'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),
      Spot(
        id: 'seed_36',
        title: 'Pigeon Park Container Gardens',
        description: 'Innovative community gardens built inside repurposed shipping containers, creating vertical growing spaces.',
        latitude: 39.9644,
        longitude: -75.1389,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 6, 18, 14, 15),
        tags: ['container-gardens', 'shipping-containers', 'vertical', 'innovative'],
        viewCount: 234,
        bookmarkCount: 45,
        visitCount: 109,
      ),

      // Fishtown
      Spot(
        id: 'seed_37',
        title: 'Penn Treaty Park Waterfront Overlook',
        description: 'The spot where William Penn allegedly signed his treaty with the Lenape, now offering Delaware River views and historic interpretation.',
        latitude: 39.9742,
        longitude: -75.1247,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 6, 12, 17, 20),
        tags: ['william-penn', 'lenape', 'delaware-river', 'historic'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),
      Spot(
        id: 'seed_38',
        title: 'Frankford Creek Confluence',
        description: 'The confluence where Frankford Creek meets the Delaware River, featuring restored wetlands and bird watching opportunities.',
        latitude: 39.9758,
        longitude: -75.1189,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 6, 8, 8, 45),
        tags: ['confluence', 'frankford-creek', 'wetlands', 'bird-watching'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),

      // South Philadelphia
      Spot(
        id: 'seed_39',
        title: 'Italian Market Mosaic Alley',
        description: 'A hidden alley off 9th Street featuring community mosaics telling the story of Italian immigration to Philadelphia.',
        latitude: 39.9356,
        longitude: -75.1578,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 6, 3, 12, 10),
        tags: ['italian-market', 'mosaic', 'immigration', 'community'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),
      Spot(
        id: 'seed_40',
        title: 'Marconi Plaza Bocce Courts',
        description: 'Traditional Italian bocce ball courts where neighborhood elders gather daily for games and conversation.',
        latitude: 39.9278,
        longitude: -75.1611,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1541919329513-35f7af297129?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 5, 28, 16, 30),
        tags: ['bocce-courts', 'italian', 'elders', 'conversation'],
        viewCount: 156,
        bookmarkCount: 30,
        visitCount: 73,
      ),
      Spot(
        id: 'seed_41',
        title: 'Mifflin Square Park Community Garden',
        description: 'A vibrant community garden where neighbors grow vegetables and flowers together, featuring a children\'s learning area.',
        latitude: 39.9289,
        longitude: -75.1533,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 5, 22, 11, 15),
        tags: ['community-garden', 'vegetables', 'children', 'learning'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // West Philadelphia
      Spot(
        id: 'seed_42',
        title: 'Clark Park Dickens Village',
        description: 'The whimsical "Dickens Village" installation featuring miniature Victorian houses and gardens created by local artists.',
        latitude: 39.9478,
        longitude: -75.2047,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 5, 18, 14, 40),
        tags: ['dickens-village', 'miniature', 'victorian', 'local-artists'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
      Spot(
        id: 'seed_43',
        title: 'Woodland Cemetery Victorian Greenhouse',
        description: 'A restored Victorian greenhouse from the 1880s housing rare plants and serving as a peaceful meditation space.',
        latitude: 39.9444,
        longitude: -75.2011,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 5, 12, 10, 25),
        tags: ['victorian-greenhouse', '1880s', 'rare-plants', 'meditation'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),
      Spot(
        id: 'seed_44',
        title: 'Bartram\'s Garden Tidal Wetlands',
        description: 'The restored tidal wetlands where Bartram conducted his botanical experiments, now home to rare native species.',
        latitude: 39.9264,
        longitude: -75.2244,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 5, 8, 9, 10),
        tags: ['tidal-wetlands', 'bartram', 'botanical', 'native-species'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),

      // Fairmount/Art Museum Area
      Spot(
        id: 'seed_45',
        title: 'Philadelphia Museum of Art East Terrace',
        description: 'The lesser-known east terrace offering intimate views of the Schuylkill River and Boathouse Row without crowds.',
        latitude: 39.9656,
        longitude: -75.1811,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 5, 3, 17, 30),
        tags: ['east-terrace', 'schuylkill', 'boathouse-row', 'intimate'],
        viewCount: 167,
        bookmarkCount: 33,
        visitCount: 78,
      ),
      Spot(
        id: 'seed_46',
        title: 'Fairmount Water Works Interpretive Center',
        description: 'The historic water works building housing interactive exhibits about Philadelphia\'s water history and engineering.',
        latitude: 39.9667,
        longitude: -75.1844,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 4, 28, 13, 15),
        tags: ['water-works', 'interactive', 'water-history', 'engineering'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),
      Spot(
        id: 'seed_47',
        title: 'Kelly Drive Boathouse Row Overlook',
        description: 'The perfect vantage point for viewing the historic boathouses reflected in the Schuylkill River, especially at golden hour.',
        latitude: 39.9694,
        longitude: -75.1889,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 4, 22, 18, 45),
        tags: ['boathouse-row', 'reflection', 'schuylkill', 'golden-hour'],
        viewCount: 289,
        bookmarkCount: 56,
        visitCount: 134,
      ),

      // Manayunk
      Spot(
        id: 'seed_48',
        title: 'Manayunk Canal Towpath Lock 68',
        description: 'The restored Lock 68 from the Manayunk Canal, demonstrating 19th-century engineering and transportation history.',
        latitude: 40.0167,
        longitude: -75.2244,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1520637836862-4d197d17c50a?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 4, 18, 11, 20),
        tags: ['lock-68', 'canal', '19th-century', 'transportation'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),
      Spot(
        id: 'seed_49',
        title: 'Main Street Manayunk Wall Mural',
        description: 'A massive mural depicting Manayunk\'s industrial heritage, visible from the Schuylkill River Trail.',
        latitude: 40.0183,
        longitude: -75.2256,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 4, 12, 15, 35),
        tags: ['wall-mural', 'industrial-heritage', 'schuylkill-trail', 'massive'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),

      // Chestnut Hill
      Spot(
        id: 'seed_50',
        title: 'Wissahickon Valley Park Forbidden Drive Bridge',
        description: 'The historic Walnut Lane Bridge spanning the Wissahickon Creek, built in 1908 and offering dramatic valley views.',
        latitude: 40.0547,
        longitude: -75.2089,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1507041957456-9c397ce39c97?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 4, 8, 12, 50),
        tags: ['walnut-lane-bridge', '1908', 'valley-views', 'historic'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),
      Spot(
        id: 'seed_51',
        title: 'Chestnut Hill College Grotto',
        description: 'A peaceful stone grotto on campus featuring a replica of the Lourdes Grotto, surrounded by gardens and walking paths.',
        latitude: 40.0722,
        longitude: -75.2067,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1520637836862-4d197d17c50a?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 4, 3, 16, 15),
        tags: ['grotto', 'lourdes', 'gardens', 'walking-paths'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // Germantown
      Spot(
        id: 'seed_52',
        title: 'Wyck Historic House Rose Garden',
        description: 'America\'s oldest rose garden, continuously cultivated since 1820, featuring over 50 heirloom varieties.',
        latitude: 40.0333,
        longitude: -75.1722,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 3, 28, 14, 30),
        tags: ['rose-garden', 'oldest', '1820', 'heirloom'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
      Spot(
        id: 'seed_53',
        title: 'Cliveden Battlefield Park',
        description: 'The site of the 1777 Battle of Germantown, with preserved Revolutionary War earthworks and interpretive trails.',
        latitude: 40.0389,
        longitude: -75.1711,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 3, 22, 10, 45),
        tags: ['battlefield', '1777', 'earthworks', 'revolutionary-war'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),

      // Kensington
      Spot(
        id: 'seed_54',
        title: 'Frankford Creek Greenway Wetlands',
        description: 'Restored urban wetlands along Frankford Creek providing habitat for migrating birds and environmental education.',
        latitude: 39.9944,
        longitude: -75.1222,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 3, 18, 8, 20),
        tags: ['wetlands', 'frankford-creek', 'migrating-birds', 'education'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),
      Spot(
        id: 'seed_55',
        title: 'Norris Square Park Day of the Dead Altar',
        description: 'An annual community altar celebrating Día de los Muertos, featuring colorful decorations and cultural programming.',
        latitude: 39.9889,
        longitude: -75.1267,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 3, 12, 17, 55),
        tags: ['day-of-dead', 'altar', 'colorful', 'cultural'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),

      // Port Richmond
      Spot(
        id: 'seed_56',
        title: 'Frankford Arsenal Historic Gatehouse',
        description: 'The preserved gatehouse of the former Frankford Arsenal, now marking the entrance to a riverside park.',
        latitude: 39.9889,
        longitude: -75.1089,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 3, 8, 13, 10),
        tags: ['arsenal', 'gatehouse', 'preserved', 'riverside'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),
      Spot(
        id: 'seed_57',
        title: 'Delaware River Trail Wetland Boardwalk',
        description: 'A wooden boardwalk through restored tidal wetlands offering bird watching and environmental education.',
        latitude: 39.9933,
        longitude: -75.1056,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1507041957456-9c397ce39c97?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 3, 3, 9, 35),
        tags: ['boardwalk', 'tidal-wetlands', 'bird-watching', 'education'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // Northeast Philadelphia
      Spot(
        id: 'seed_58',
        title: 'Pennypack Creek Covered Bridge',
        description: 'A historic covered bridge over Pennypack Creek, one of the few remaining covered bridges in Philadelphia.',
        latitude: 40.0794,
        longitude: -75.0889,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1507041957456-9c397ce39c97?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 2, 26, 14, 20),
        tags: ['covered-bridge', 'pennypack-creek', 'historic', 'remaining'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),
      Spot(
        id: 'seed_59',
        title: 'Fox Chase Farm Heritage Orchard',
        description: 'A restored heritage apple orchard featuring varieties from the 1700s, maintained by community volunteers.',
        latitude: 40.0944,
        longitude: -75.0811,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 2, 22, 11, 45),
        tags: ['heritage-orchard', 'apple', '1700s', 'volunteers'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),

      // North Philadelphia
      Spot(
        id: 'seed_60',
        title: 'Hunting Park Recreation Center Mural',
        description: 'A community-painted mural covering the entire recreation center, depicting the neighborhood\'s resilience and hope.',
        latitude: 40.0167,
        longitude: -75.1422,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 2, 18, 15, 30),
        tags: ['recreation-center', 'community-painted', 'resilience', 'hope'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),
      Spot(
        id: 'seed_61',
        title: 'Nicetown Tioga Community Garden',
        description: 'A thriving community garden built on former vacant lots, featuring raised beds and a greenhouse.',
        latitude: 40.0111,
        longitude: -75.1556,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 2, 12, 10, 15),
        tags: ['community-garden', 'vacant-lots', 'raised-beds', 'greenhouse'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),

      // Brewerytown
      Spot(
        id: 'seed_62',
        title: 'Girard College Chapel Bell Tower',
        description: 'The historic bell tower of Girard College Chapel, offering guided tours with panoramic city views.',
        latitude: 39.9722,
        longitude: -75.1756,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 2, 8, 16, 40),
        tags: ['bell-tower', 'girard-college', 'guided-tours', 'panoramic'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
      Spot(
        id: 'seed_63',
        title: 'Brewery Arts District Sculpture Walk',
        description: 'An outdoor sculpture installation featuring works by local artists throughout the historic brewery district.',
        latitude: 39.9756,
        longitude: -75.1789,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 2, 3, 12, 25),
        tags: ['sculpture-walk', 'local-artists', 'brewery-district', 'installation'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // Strawberry Mansion
      Spot(
        id: 'seed_64',
        title: 'Strawberry Mansion Bridge River Platform',
        description: 'A fishing platform beneath the historic bridge with excellent views of the Schuylkill River and Boathouse Row.',
        latitude: 39.9811,
        longitude: -75.1844,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 1, 28, 7, 50),
        tags: ['fishing-platform', 'historic-bridge', 'schuylkill', 'boathouse'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),
      Spot(
        id: 'seed_65',
        title: 'Strawberry Mansion Historic House Gardens',
        description: 'The restored 19th-century gardens surrounding the historic mansion, featuring period-appropriate plantings.',
        latitude: 39.9833,
        longitude: -75.1867,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 1, 22, 13, 15),
        tags: ['historic-house', '19th-century', 'restored', 'period-appropriate'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),

      // Point Breeze
      Spot(
        id: 'seed_66',
        title: 'Point Breeze Avenue Mural Mile',
        description: 'A stretch of Point Breeze Avenue featuring continuous murals depicting the neighborhood\'s African American heritage.',
        latitude: 39.9278,
        longitude: -75.1811,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 1, 18, 14, 30),
        tags: ['mural-mile', 'continuous', 'african-american', 'heritage'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),
      Spot(
        id: 'seed_67',
        title: 'Wharton Square Park Community Orchard',
        description: 'A neighborhood orchard featuring fruit trees maintained by residents, with seasonal harvest festivals.',
        latitude: 39.9267,
        longitude: -75.1756,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 1, 12, 11, 20),
        tags: ['community-orchard', 'fruit-trees', 'residents', 'harvest-festivals'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),

      // Grays Ferry
      Spot(
        id: 'seed_68',
        title: 'Schuylkill River Park Dog Run Island',
        description: 'A unique fenced dog park on a small island in the Schuylkill River, accessible by a short bridge.',
        latitude: 39.9356,
        longitude: -75.1933,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 1, 8, 16, 45),
        tags: ['dog-park', 'island', 'schuylkill', 'bridge'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),
      Spot(
        id: 'seed_69',
        title: 'Grays Ferry Crescent Trail Art Installations',
        description: 'Rotating art installations along the Crescent Trail, featuring works that respond to the river environment.',
        latitude: 39.9389,
        longitude: -75.1911,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2024, 1, 3, 9, 30),
        tags: ['art-installations', 'rotating', 'crescent-trail', 'river-environment'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // Queen Village
      Spot(
        id: 'seed_70',
        title: 'Shot Tower Park Historic Shot Tower',
        description: 'The preserved 1808 shot tower where lead shot was manufactured, now a National Historic Landmark.',
        latitude: 39.9356,
        longitude: -75.1467,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 12, 28, 14, 20),
        tags: ['shot-tower', '1808', 'lead-shot', 'historic-landmark'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
      Spot(
        id: 'seed_71',
        title: 'Fabric Row Historic District',
        description: 'The historic fabric district on 4th Street where Jewish immigrants established textile businesses in the early 1900s.',
        latitude: 39.9322,
        longitude: -75.1489,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 12, 22, 12, 10),
        tags: ['fabric-row', 'jewish-immigrants', 'textile', 'early-1900s'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),

      // Bella Vista
      Spot(
        id: 'seed_72',
        title: 'Ralph Bunche Elementary Rain Garden',
        description: 'An innovative rain garden at the elementary school demonstrating sustainable stormwater management to students.',
        latitude: 39.9311,
        longitude: -75.1578,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 12, 18, 10, 35),
        tags: ['rain-garden', 'elementary', 'stormwater', 'sustainable'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),
      Spot(
        id: 'seed_73',
        title: 'Mario Lanza Park Fountain',
        description: 'A beautiful fountain dedicated to the famous tenor Mario Lanza, surrounded by Italian-inspired landscaping.',
        latitude: 39.9289,
        longitude: -75.1556,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1541919329513-35f7af297129?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 12, 12, 15, 25),
        tags: ['mario-lanza', 'fountain', 'tenor', 'italian-inspired'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),

      // Passyunk Square
      Spot(
        id: 'seed_74',
        title: 'Singing Fountain at 11th and Bigler',
        description: 'A unique fountain that plays music on the hour, created by local artists and community members.',
        latitude: 39.9244,
        longitude: -75.1633,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 12, 8, 17, 40),
        tags: ['singing-fountain', 'music', 'hourly', 'community'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),
      Spot(
        id: 'seed_75',
        title: 'East Passyunk Triangle Mural',
        description: 'A massive corner mural depicting the neighborhood\'s transformation from industrial to culinary destination.',
        latitude: 39.9222,
        longitude: -75.1611,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 12, 3, 13, 15),
        tags: ['corner-mural', 'transformation', 'industrial', 'culinary'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // Pennsport
      Spot(
        id: 'seed_76',
        title: 'Columbus Square Park Community Garden',
        description: 'A neighborhood garden where Italian-American families have grown tomatoes and herbs for generations.',
        latitude: 39.9267,
        longitude: -75.1422,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 11, 28, 11, 50),
        tags: ['columbus-square', 'italian-american', 'tomatoes', 'generations'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),
      Spot(
        id: 'seed_77',
        title: 'Dickinson Square West Pocket Park',
        description: 'A tiny triangular park featuring native plants and a small playground, built on a former vacant lot.',
        latitude: 39.9233,
        longitude: -75.1567,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 11, 22, 9, 20),
        tags: ['triangular-park', 'native-plants', 'playground', 'vacant-lot'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),

      // Graduate Hospital
      Spot(
        id: 'seed_78',
        title: 'Seger Park Recreation Center Green Roof',
        description: 'An accessible green roof demonstration project featuring native plants and rainwater collection systems.',
        latitude: 39.9378,
        longitude: -75.1689,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 11, 18, 14, 35),
        tags: ['green-roof', 'demonstration', 'rainwater', 'collection'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),
      Spot(
        id: 'seed_79',
        title: 'Fitler Square Dog Park Pavilion',
        description: 'A covered pavilion in the dog park providing shade and featuring community bulletin boards.',
        latitude: 39.9444,
        longitude: -75.1756,
        category: SpotCategory.quiet,
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 11, 12, 16, 10),
        tags: ['dog-park', 'pavilion', 'shade', 'bulletin-boards'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),

      // Logan Square
      Spot(
        id: 'seed_80',
        title: 'Logan Circle Fountain Night Illumination',
        description: 'The stunning nighttime illumination of the Swann Memorial Fountain, creating dramatic light and water displays.',
        latitude: 39.9583,
        longitude: -75.1711,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 11, 8, 19, 30),
        tags: ['fountain', 'illumination', 'swann-memorial', 'light-displays'],
        viewCount: 267,
        bookmarkCount: 52,
        visitCount: 124,
      ),
      Spot(
        id: 'seed_81',
        title: 'Cathedral Basilica of Saints Peter and Paul Steps',
        description: 'The grand limestone steps of the cathedral, a popular gathering place and architectural photography spot.',
        latitude: 39.9575,
        longitude: -75.1717,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 11, 3, 12, 45),
        tags: ['cathedral', 'limestone-steps', 'gathering', 'architectural'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),

      // Francisville
      Spot(
        id: 'seed_82',
        title: 'Francisville Recreation Center Mural',
        description: 'A vibrant community mural celebrating the neighborhood\'s cultural diversity and resilience.',
        latitude: 39.9722,
        longitude: -75.1689,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 10, 28, 15, 20),
        tags: ['recreation-center', 'diversity', 'resilience', 'vibrant'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),
      Spot(
        id: 'seed_83',
        title: 'Spring Garden Bridge Overlook',
        description: 'The pedestrian walkway on Spring Garden Street Bridge offering elevated views of the Schuylkill River.',
        latitude: 39.9678,
        longitude: -75.1756,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 10, 22, 17, 10),
        tags: ['pedestrian-walkway', 'spring-garden', 'elevated-views', 'schuylkill'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // Callowhill
      Spot(
        id: 'seed_84',
        title: 'Rail Park Phase 1 Elevated Garden',
        description: 'The first phase of the Rail Park featuring elevated gardens built on former railway infrastructure.',
        latitude: 39.9633,
        longitude: -75.1589,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 10, 18, 11, 30),
        tags: ['rail-park', 'elevated-gardens', 'railway', 'infrastructure'],
        viewCount: 289,
        bookmarkCount: 56,
        visitCount: 134,
      ),
      Spot(
        id: 'seed_85',
        title: 'Chinatown Friendship Gate',
        description: 'The ornate traditional Chinese gate marking the entrance to Chinatown, gifted by Philadelphia\'s sister city Tianjin.',
        latitude: 39.9558,
        longitude: -75.1567,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 10, 12, 14, 15),
        tags: ['friendship-gate', 'chinese', 'chinatown', 'tianjin'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),

      // Spring Garden
      Spot(
        id: 'seed_86',
        title: 'Eastern State Penitentiary Art Installations',
        description: 'Contemporary art installations within the historic prison ruins, creating powerful juxtapositions of past and present.',
        latitude: 39.9683,
        longitude: -75.1722,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1520637836862-4d197d17c50a?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 10, 8, 16, 40),
        tags: ['eastern-state', 'art-installations', 'prison-ruins', 'juxtapositions'],
        viewCount: 245,
        bookmarkCount: 48,
        visitCount: 115,
      ),
      Spot(
        id: 'seed_87',
        title: 'Haas Playground Community Garden',
        description: 'A community garden adjacent to the playground where families grow vegetables and flowers together.',
        latitude: 39.9661,
        longitude: -75.1644,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 10, 3, 10, 25),
        tags: ['haas-playground', 'community-garden', 'families', 'vegetables'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),

      // Kingsessing (Southwest Philadelphia)
      Spot(
        id: 'seed_88',
        title: 'Bartram\'s Garden Historic Greenhouse',
        description: 'America\'s oldest surviving botanic garden greenhouse, where John Bartram conducted pioneering botanical research.',
        latitude: 39.9256,
        longitude: -75.2256,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 9, 28, 13, 50),
        tags: ['greenhouse', 'oldest', 'john-bartram', 'botanical-research'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
      Spot(
        id: 'seed_89',
        title: 'Elmwood Park Zoo Education Center',
        description: 'An interactive education center featuring native Pennsylvania wildlife and conservation programs.',
        latitude: 39.9189,
        longitude: -75.2167,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 9, 22, 12, 15),
        tags: ['education-center', 'native-wildlife', 'pennsylvania', 'conservation'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),

      // Overbrook
      Spot(
        id: 'seed_90',
        title: 'Overbrook Recreation Center Historic WPA Building',
        description: 'A Works Progress Administration building from the 1930s featuring beautiful Art Deco architectural details.',
        latitude: 39.9733,
        longitude: -75.2422,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 9, 18, 15, 30),
        tags: ['wpa', '1930s', 'art-deco', 'architectural'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),
      Spot(
        id: 'seed_91',
        title: 'Morris Park Hidden Meadow',
        description: 'A wildflower meadow tucked behind the community center, popular with butterfly watchers and nature photographers.',
        latitude: 39.9811,
        longitude: -75.2356,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 9, 12, 8, 45),
        tags: ['wildflower-meadow', 'butterfly-watchers', 'nature-photographers', 'hidden'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),

      // East Mount Airy
      Spot(
        id: 'seed_92',
        title: 'Weavers Way Co-op Demonstration Garden',
        description: 'An organic demonstration garden behind the co-op showing sustainable urban farming techniques.',
        latitude: 40.0556,
        longitude: -75.1889,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 9, 8, 11, 20),
        tags: ['demonstration-garden', 'organic', 'sustainable', 'urban-farming'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),
      Spot(
        id: 'seed_93',
        title: 'Johnson House Historic Underground Railroad Site',
        description: 'A preserved Underground Railroad station where enslaved people found refuge on their journey to freedom.',
        latitude: 40.0522,
        longitude: -75.1922,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 9, 3, 14, 35),
        tags: ['underground-railroad', 'enslaved-people', 'refuge', 'freedom'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),

      // West Oak Lane
      Spot(
        id: 'seed_94',
        title: 'Carpenters\' Woods Nature Preserve',
        description: 'A 54-acre nature preserve featuring old-growth forest and hiking trails within the city limits.',
        latitude: 40.0644,
        longitude: -75.1656,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 8, 28, 16, 50),
        tags: ['nature-preserve', '54-acres', 'old-growth', 'hiking-trails'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),
      Spot(
        id: 'seed_95',
        title: 'Ogontz Avenue Mural Corridor',
        description: 'A series of murals along Ogontz Avenue celebrating the neighborhood\'s African American history and culture.',
        latitude: 40.0478,
        longitude: -75.1556,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 8, 22, 13, 25),
        tags: ['mural-corridor', 'ogontz-avenue', 'african-american', 'history'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),

      // Tacony
      Spot(
        id: 'seed_96',
        title: 'Tacony Creek Park Restored Wetlands',
        description: 'Restored tidal wetlands at the mouth of Tacony Creek providing habitat for migrating waterfowl.',
        latitude: 40.0444,
        longitude: -75.0889,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 8, 18, 9, 10),
        tags: ['restored-wetlands', 'tacony-creek', 'migrating', 'waterfowl'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),
      Spot(
        id: 'seed_97',
        title: 'Disston Saw Works Historic Clock Tower',
        description: 'The preserved clock tower from the historic Disston Saw Works, now a landmark in the revitalized area.',
        latitude: 40.0411,
        longitude: -75.0878,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 8, 12, 15, 40),
        tags: ['disston-saw', 'clock-tower', 'preserved', 'revitalized'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),

      // Holmesburg
      Spot(
        id: 'seed_98',
        title: 'Pennypack Environmental Center Butterfly Garden',
        description: 'A native butterfly garden featuring plants that support monarch and swallowtail butterfly populations.',
        latitude: 40.0817,
        longitude: -75.0622,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 8, 8, 12, 30),
        tags: ['butterfly-garden', 'monarch', 'swallowtail', 'native-plants'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
      Spot(
        id: 'seed_99',
        title: 'Holmesburg Junction Historic Train Station',
        description: 'A beautifully restored 1920s train station now serving as a community center and museum.',
        latitude: 40.0789,
        longitude: -75.0656,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 8, 3, 16, 15),
        tags: ['train-station', '1920s', 'restored', 'community-center'],
        viewCount: 145,
        bookmarkCount: 28,
        visitCount: 67,
      ),

      // Roxborough
      Spot(
        id: 'seed_100',
        title: 'Schuylkill Center Widener Visitor Center',
        description: 'An award-winning green building showcasing sustainable design principles and native plant landscaping.',
        latitude: 40.0722,
        longitude: -75.2233,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 7, 28, 11, 45),
        tags: ['visitor-center', 'green-building', 'sustainable', 'native-plants'],
        viewCount: 189,
        bookmarkCount: 37,
        visitCount: 88,
      ),
      Spot(
        id: 'seed_101',
        title: 'Wissahickon Transfer Station Overlook',
        description: 'A scenic overlook at the Wissahickon Transfer Station offering panoramic views of the Schuylkill River valley.',
        latitude: 40.0667,
        longitude: -75.2178,
        category: SpotCategory.views,
        imageUrl: 'https://images.unsplash.com/photo-1444927714506-8492d94b5ba0?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 7, 22, 18, 20),
        tags: ['transfer-station', 'overlook', 'panoramic', 'river-valley'],
        viewCount: 201,
        bookmarkCount: 39,
        visitCount: 94,
      ),

      // Additional Media, PA spots
      Spot(
        id: 'seed_102',
        title: 'Springton Manor Farm Historic Barn',
        description: 'A preserved 18th-century stone barn demonstrating colonial farming techniques and housing heritage livestock.',
        latitude: 39.9156,
        longitude: -75.4089,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 7, 18, 14, 30),
        tags: ['springton-manor', 'stone-barn', 'colonial', 'heritage-livestock'],
        viewCount: 156,
        bookmarkCount: 31,
        visitCount: 73,
      ),
      Spot(
        id: 'seed_103',
        title: 'Rose Tree Park Amphitheater',
        description: 'A natural grass amphitheater hosting summer concerts and community events in a beautiful park setting.',
        latitude: 39.9044,
        longitude: -75.4156,
        category: SpotCategory.art,
        imageUrl: 'https://images.unsplash.com/photo-1541919329513-35f7af297129?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 7, 12, 19, 15),
        tags: ['amphitheater', 'summer-concerts', 'community-events', 'grass'],
        viewCount: 178,
        bookmarkCount: 35,
        visitCount: 83,
      ),
      Spot(
        id: 'seed_104',
        title: 'Media Elementary School Peace Garden',
        description: 'A student-designed peace garden featuring symbols from different cultures and meditation areas.',
        latitude: 39.9189,
        longitude: -75.3844,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 7, 8, 10, 40),
        tags: ['peace-garden', 'student-designed', 'cultural-symbols', 'meditation'],
        viewCount: 167,
        bookmarkCount: 32,
        visitCount: 78,
      ),
      Spot(
        id: 'seed_105',
        title: 'Glen Providence Park Waterfall Trail',
        description: 'A short hiking trail leading to a hidden waterfall in the heart of Media, popular with local families.',
        latitude: 39.9133,
        longitude: -75.3911,
        category: SpotCategory.nature,
        imageUrl: 'https://images.unsplash.com/photo-1507041957456-9c397ce39c97?w=800&q=80',
        createdBy: 'lorenzaparentado',
        createdAt: DateTime(2023, 7, 3, 16, 25),
        tags: ['waterfall-trail', 'hidden-waterfall', 'hiking', 'families'],
        viewCount: 234,
        bookmarkCount: 46,
        visitCount: 109,
      ),
    ];
  }
}